version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mcp-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=crm
    networks:
      - mcp-network

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: mcp-server
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DB=crm
      - MONGO_COLLECTION=customers
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
    depends_on:
      - mongodb
    networks:
      - mcp-network

  web-ui:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: mcp-web-ui
    restart: always
    ports:
      - "8080:8000"
    environment:
      - API_KEY=${API_KEY}
      - MCP_SERVER_URL=http://mcp-server:8000
      - BASE_URL=${BASE_URL}
    depends_on:
      - mcp-server
    networks:
      - mcp-network

volumes:
  mongodb_data:

networks:
  mcp-network:
    driver: bridge
